name: Pipeline

on:
  push:
    branches:
      - main
      - sebastianDevelopment

  pull_request:
    branches:
      - main
      - sebastianDevelopment

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node packages
        run: npm install

      - name: Start application
        run: |
          docker run -d \
            --name my-api \
            -p 3000:3000 \
            -e DATABASE_URL=postgres://user:password@host:port/mydatabase \
            

      - name: Wait for application to be ready
        run: |
          until curl -s http://localhost:3000/health; do
            echo "Waiting for application to be ready..."
            sleep 2
          done

      - name: Run Playwright tests
        run: npx playwright test

      - name: Save test run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./playwright-report
          if-no-files-found: warn
          include-hidden-files: false
