name: Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Node packages
        run: npm install

      
      - name: Docker image
        run: docker pull thirsty_rubin/my-vue-app:v1

      - name: Start application
        run: docker run -d -p 3000:3000 thirsty_rubin/my-vue-app:<none>

      - name: Run Playwright tests
        run: npx playwright test

      - name: Save test run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./playwright-report
          if-no-files-found: warn
          include-hidden-files: false
